project:
  type: website
  output-dir: docs

website:
  title: "Dulce Rodriguez"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects and Publications
      - href: resume1.html
        text: Resume
      - href: media/Resume2025.pdf
        text: CV

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    page-layout: full

editor: visual

