project:
  type: website
  output-dir: docs

website:
  title: "Dulce Rodriguez"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects and Publications
      - href: Resume.qmd
        text: Resume

format:
  html:
    theme: 
      light: minty
      dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual

