---
title: "Projects and Publications"
---

## Projects
1. **Housing Crisis through Time Series**  
   - This project investigates monthly U.S. housing starts from 1965 to 1975, applying time series analysis techniques to understand and predict future activity. After splitting the data, I used transformations (Box-Cox) and differencing to address non constant variance and seasonality. I then examined ACF/PACF plots for our model selection. Among several candidate ARIMA/SARIMA models, a seasonal ARIMA with Box-Cox transformation provided the best fit based on AICc and residual diagnostics. The resulting forecasts suggest relatively stable future housing starts with widening uncertainty over time. This shows how a standard time series methods can provide practical insights into housing market trends. This project was developed using R studio, markdown. 
.  

2. **Amazon Product Recommendation system**  
   - In this project, we developed a recommendation system using an Amazon dataset to enhance user experience by providing personalized product recommendations. With the vast amount of data available in e-commerce, recommendation systems play a crucial role in helping users discover relevant products efficiently. By leveraging machine learning techniques, we aim to build a model that predicts user preferences based on historical interactions and product attributes. This project was developed using Python and Quarto, R studio.

3. **World Happiness by GDP Report and App**
  - This project aims to analyze World Happiness Report 2023 data to determine if the mean "happiness" of a country is significantly different and changes over time differently in countries with a low versus high log GDP per capita. Linear regression models and exploratory data analysis techniques were applied to answer these questions. The results suggests that countries with a high GDP have overall higher Life ladder scores and positive affect scores than countries with a low GDP, but the trends over time show unexpected peaks where this gap is bridged. Overall, analyzing world happiness report data can help identify important characteristics of a country that keep citizens happy. In addition, I was able to generate a Shiny App that showcase interesting aspect and the findings while keeping it interactive. The app includes PCA-related analyses and is a visualizations-based app, allowing the user to add aesthetics to encode additional information on variables. 
  
4. **Portfolio Website**  
   - A personal portfolio website highlighting projects and achievements, designed with Quarto and hosted on GitHub Pages.  

## Publications
1. **"Summer Drives"**  
   - Published in UCSB’s *Starting Lines* (Fall 2024).  

## Posters
1. **"Elliptical Curves through Machine Learning"**  
   - Through the UCSB Math Direct Reading Program, Spring 2024.  

